### PR TITLE
optimized state settings in GFXD3D11Stateblock

### PR DESCRIPTION
**Pull request by ZeroFault**
This makes the state changes only happen when when they actually change from the previous state block.

### CODE REVIEW

**Comment by rextimmy** [comment]
Nice work, thanks :+1:

**Comment by rextimmy** [comment]
Hey sorry i had to revert this one, it causes a lot of rendering glitches. Will have to have a double check of it.

**Comment by ZeroFault** [comment]
Hmm, I can't find any rendering glitches you are speaking of. Could you show me an example of what is not working so I can fix it?

**Comment by rextimmy** [comment]
Yeah sure, vid from jeff https://www.youtube.com/watch?v=PzeqTzKRCIA&feature=youtu.be . You will see it the outpost too

**Comment by rextimmy** [comment]
Oh yeah just so you know i will be moving everything into dx11_clean branch today after i do a bit of whitespace cleanup etc and that will be PR'd to the official repo, than i am moving straight into phase 2 which is re-writing the constant buffer stuff and other performance related issues. Might be better to target that branch.

**Comment by ZeroFault** [comment]
I just fixed the rendering issues from the pull request. It just wasn't the calculating the correct update range for the sampler slots. Would you rather me wait for when you put up your optimization branch?

**Comment by rextimmy** [comment]
Ok nice work mate, yeah wait for the clean branch so that way the commit doesn't lose your name. I have tried my best to credit everyone (including yourself) for the work done previously but all of that commit history is lost now.

**Comment by rextimmy** [comment]
Hey sorry about the confusion with all this, was just bad all timing. Anyways feel free to chuck that PR at dx11_phase2 branch.

**Pull request merged**
